name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit